#!/bin/bash

iproute2_dir=/tmp/iptables
output_dir=pdfs

function toPDF()
{
  page=$1
  filename=`basename -s .8 $page`.pdf
  echo "$page => $filename"
  man -t $page | ps2pdf - > $output_dir/$filename
}

if [[ $1 != "" ]]; then
  toPDF $1
  exit
fi

cp -r $iproute2_dir/man/ man
mkdir -pv $output_dir
for page in `find man -type f|grep -v gitignore|grep -v Makefile`
do
  toPDF $page
done
